permalink: /:lang/blog/:title
pygments: false

# we need kramdown here, since we have markdown in <div> blocks
# which is not supported by rdiscount
markdown: kramdown

lsi: false
url: http://localhost:4000
canonicalurl: http://www.spamihilator.com
newsletterserviceurl: http://www.spamihilator.com/newsletter
exclude: [ config.rb, sass, Gemfile, Gemfile.lock, README.md ]
