permalink: /:lang/blog/:title
pygments: false

# we need kramdown here, since we have markdown in <div> blocks
# which is not supported by rdiscount
markdown: kramdown

lsi: false
url: https://www.spamihilator.com
canonicalurl: https://www.spamihilator.com
newsletterserviceurl: https://www.spamihilator.com/newsletter
exclude: [ config.rb, sass, Gemfile, Gemfile.lock, README.md, Dockerfile ]
